"""Backtesting engine for the cross‑sectional momentum strategy.

This script takes the most recent price panel and the corresponding
volatility‑scaled weights generated by ``signal_generation.py`` and
computes the strategy’s historical performance.  It also produces
visualisations of the equity curve and outputs summary statistics such
as cumulative return, annualised return, annualised volatility,
Sharpe ratio and maximum drawdown.

The methodology follows industry best practices: returns are computed
using simple percentage changes, weights are lagged by one day to
avoid look‑ahead bias, and performance metrics are annualised using
252 trading days【511009017126348†L84-L96】.  Drawdowns are computed
relative to the running maximum of the cumulative return series.  The
resulting equity curve chart is saved to disk for visual inspection.

References
----------
* Jegadeesh, N., & Titman, S. (1993). Returns to buying winners and
  selling losers: Implications for stock market efficiency.  This
  seminal paper lays the groundwork for momentum strategies and
  emphasises the importance of rigorous backtesting.
* Moreira, A., & Muir, T. (2017). Volatility‑managed portfolios.  The
  authors show that scaling portfolio exposures by volatility can
  significantly reduce drawdowns and improve Sharpe ratios【511009017126348†L146-L152】.
* Pyry Pohjantähti (2024). Revisiting (Revitalizing) Momentum.  The
  study notes that the profitability of cross‑sectional momentum has
  declined and highlights techniques such as volatility scaling and
  market state conditioning to enhance performance【416002924589760†L81-L113】.

Usage
-----
Run this script after ``trade_algorithm.py`` and ``signal_generation.py``
have been executed.  It will automatically locate the most recent
``adjclose_wide_*.csv`` file in ``data/prices`` and the most recent
``weights_cs_*.csv`` file in ``data/signals``, compute returns and
generate performance outputs.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def load_latest_files(base_dir: Path) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Load the most recent price panel and weights file.

    Parameters
    ----------
    base_dir : pathlib.Path
        Root directory of the project.  The function looks for
        ``data/prices`` and ``data/signals`` subdirectories relative
        to this path.

    Returns
    -------
    (prices, weights) : tuple of pandas.DataFrame
        The latest wide price DataFrame (dates x tickers) and the
        latest weights DataFrame (dates x tickers).  Both are indexed
        by dates and share the same column set.
    """
    # Locate price files
    prices_dir = base_dir / "data" / "prices"
    signals_dir = base_dir / "data" / "signals"
    # Fallback to parent directory if local path does not exist
    if not prices_dir.exists():
        alt_prices_dir = base_dir.parent / "data" / "prices"
        if alt_prices_dir.exists():
            prices_dir = alt_prices_dir
    if not signals_dir.exists():
        alt_signals_dir = base_dir.parent / "data" / "signals"
        if alt_signals_dir.exists():
            signals_dir = alt_signals_dir
    price_files = sorted(prices_dir.glob("adjclose_wide_*.csv"))
    weight_files = sorted(signals_dir.glob("weights_cs_*.csv"))
    if not price_files:
        raise FileNotFoundError(f"No adjclose_wide CSV files found in {prices_dir}")
    if not weight_files:
        raise FileNotFoundError(f"No weights_cs CSV files found in {signals_dir}")
    price_path = price_files[-1]
    weight_path = weight_files[-1]
    # Load data
    prices = pd.read_csv(price_path, index_col=0, parse_dates=True)
    weights = pd.read_csv(weight_path, index_col=0, parse_dates=True)
    # Standardise index names
    prices.index.name = "Date"
    weights.index.name = "Date"
    return prices, weights


def compute_portfolio_returns(prices: pd.DataFrame,weights: pd.DataFrame,cost_bps: float = 5.0) -> pd.Series:
    """Compute daily portfolio returns with lagged weights.

    Parameters
    ----------
    prices : pandas.DataFrame
        Wide DataFrame of adjusted close prices.
    weights : pandas.DataFrame
        DataFrame of portfolio weights (positive for long, negative for
        short) where rows correspond to dates and columns correspond to
        tickers.  Weights are assumed to sum to zero net exposure
        (long weights sum to 1, short weights sum to ‑1).

    Returns
    -------
    pandas.Series
        Series of daily portfolio returns.  The index aligns with
        ``prices`` and ``weights`` after the initial shift.
    """
    asset_returns = prices.pct_change().dropna(how="all")
    w = weights.reindex(asset_returns.index).fillna(0.0)
    turnover = w.diff().abs().sum(axis=1).fillna(0.0)
    aligned_weights = w.shift(1).fillna(0.0)
    gross_ret = (aligned_weights * asset_returns).sum(axis=1)
    cost = turnover * (cost_bps / 10_000.0)
    net_ret = gross_ret - cost
    return net_ret


def compute_performance_metrics(returns: pd.Series) -> Dict[str, float]:
    """Compute key performance metrics for a return series.

    Metrics include cumulative return, annualised return, annualised
    volatility, Sharpe ratio and maximum drawdown.  The Sharpe ratio
    assumes a zero risk‑free rate for simplicity.

    Parameters
    ----------
    returns : pandas.Series
        Series of daily portfolio returns.

    Returns
    -------
    dict
        Dictionary of performance metrics.
    """
    if returns.empty:
        raise ValueError("Return series is empty; cannot compute metrics.")
    # Cumulative return
    cum_curve = (1.0 + returns).cumprod()
    total_return = cum_curve.iloc[-1] - 1.0
    # Annualised return using 252 trading days
    n_days = len(returns)
    ann_return = (1.0 + total_return) ** (252.0 / n_days) - 1.0
    # Annualised volatility
    ann_vol = returns.std(ddof=0) * np.sqrt(252.0)
    # Sharpe ratio (assuming zero risk‑free rate)
    sharpe = ann_return / ann_vol if ann_vol != 0.0 else np.nan
    # Maximum drawdown
    running_max = cum_curve.cummax()
    drawdowns = cum_curve / running_max - 1.0
    max_dd = drawdowns.min()
    return {
        "cumulative_return": float(total_return),
        "annualized_return": float(ann_return),
        "annualized_volatility": float(ann_vol),
        "sharpe_ratio": float(sharpe),
        "max_drawdown": float(max_dd),
    }


def plot_equity_curve(returns: pd.Series, out_dir: Path) -> Path:
    """Plot and save the equity curve of the strategy.

    Parameters
    ----------
    returns : pandas.Series
        Series of daily portfolio returns.
    out_dir : pathlib.Path
        Directory where the plot will be saved.

    Returns
    -------
    pathlib.Path
        Path to the saved PNG file.
    """
    cum_curve = (1.0 + returns).cumprod()
    plt.figure(figsize=(10, 6))
    cum_curve.plot()
    plt.title("Equity Curve of Cross‑Sectional Momentum Strategy")
    plt.xlabel("Date")
    plt.ylabel("Cumulative Return")
    plt.grid(True)
    # Create output directory if needed
    out_dir.mkdir(parents=True, exist_ok=True)
    file_path = out_dir / f"equity_curve_{date.today()}.png"
    plt.savefig(file_path)
    plt.close()
    return file_path


def main() -> None:
    """Main entry point for backtesting.

    This function orchestrates loading data, computing returns and
    metrics, generating the equity curve plot and writing outputs to
    disk.
    """
    base_dir = Path(__file__).resolve().parent
    # Load latest price and weight files
    prices, weights = load_latest_files(base_dir)
    # Compute portfolio returns
    port_ret = compute_portfolio_returns(prices, weights)
    # Compute performance metrics
    metrics = compute_performance_metrics(port_ret)
    # Plot equity curve
    metrics["cost_bps"] = 5.0
    out_dir = base_dir / "data" / "signals"
    equity_curve_path = plot_equity_curve(port_ret, out_dir)
    # Save metrics to a CSV
    metrics_df = pd.DataFrame([metrics])
    metrics_path = out_dir / f"metrics_{date.today()}.csv"
    metrics_df.to_csv(metrics_path, index=False)
    # Print summary to the console
    print("Performance metrics:")
    for k, v in metrics.items():
        print(f"  {k}: {v:.4f}")
    print(f"Equity curve saved to: {equity_curve_path}")
    print(f"Metrics saved to: {metrics_path}")


if __name__ == "__main__":
    main()