"""Generate momentum signals and volatility‑scaled weights from price data.

This script produces trading signals based on **cross‑sectional momentum** and
adjusts them using **volatility scaling**, following best practices in
quantitative finance.  Unlike time‑series momentum, which takes signals from
an asset’s own past returns, cross‑sectional momentum ranks assets relative
to each other: the strongest performers are bought and the weakest are
sold【416002924589760†L24-L33】.  Research shows that portfolio design choices
(ranking horizon, weighting scheme) materially affect returns and risk
【511009017126348†L84-L96】, and that scaling positions by their recent
volatility reduces drawdowns and improves risk‑adjusted performance【511009017126348†L146-L152】.

The workflow implemented here is:

1. **Load the most recent price panel** generated by the data ingestion
   pipeline.  This wide DataFrame has dates on the index and tickers in the
   columns, containing adjusted close prices.  It is produced by
   ``price_loader.save_prices_panel`` and saved under ``data/prices``.
2. **Compute engineered features** using the ``feature_engineering`` module.
   We request log returns, volatility estimates, drawdowns, trend indicators
   and cross‑sectional ranks of the 252‑day (12‑month) log return.  Cross‑
   sectional ranks are essential for relative momentum strategies【416002924589760†L24-L33】.
3. **Construct signals**: we take the cross‑sectional percentile rank of the
   252‑day return and assign a long (+1) position to assets in the top 20%
   and a short (‑1) position to assets in the bottom 20%.  Positions in
   the middle 60% are set to 0.  This long‑short framework reflects the
   classical momentum factor【416002924589760†L81-L113】.
4. **Apply volatility scaling**: raw signals are divided by each asset’s
   63‑day (three month) rolling volatility.  Scaling by volatility helps
   mitigate crash risk and improves Sharpe ratios, as documented in
   financial research【511009017126348†L146-L152】.  We then normalise the
   weights so that the sum of absolute weights equals 1 on each date.
5. **Write outputs**: signals and scaled weights are stored in
   ``data/signals`` with a date stamp.  These CSV files can be consumed
   by a portfolio construction or backtesting engine.

Note
----
The script assumes that the data ingestion pipeline has been run for the
current date.  If multiple price panels exist, it selects the most recent
one.  Missing volatility values or division by zero are handled by
replacing infinite weights with zeros.  Users may adjust the long and
short percentiles (e.g. 10%/10% or 30%/30%) or choose different
volatility windows according to their research findings.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Tuple

import numpy as np
import pandas as pd

from feature_engineering import build_features


def load_latest_price_panel(prices_dir: Path) -> pd.DataFrame:
    """Load the most recent wide price panel from ``prices_dir``.

    Parameters
    ----------
    prices_dir : pathlib.Path
        Directory containing files of the form ``adjclose_wide_YYYY-MM-DD.csv``.

    Returns
    -------
    pandas.DataFrame
        Wide DataFrame of adjusted closing prices indexed by date and
        with tickers as columns.
    """
    csv_files = sorted(prices_dir.glob("adjclose_wide_*.csv"))
    if not csv_files:
        raise FileNotFoundError(f"No adjclose_wide CSV files found in {prices_dir}")
    latest = csv_files[-1]
    df = pd.read_csv(latest, index_col=0, parse_dates=True)
    df.index.name = "Date"
    return df


def compute_cs_momentum_signals(
    cs_rank: pd.DataFrame,
    long_pct: float = 0.2,
    short_pct: float = 0.2,
) -> pd.DataFrame:
    """Generate long‑short signals from cross‑sectional ranks.

    Assets with ranks greater than or equal to ``1 - long_pct`` are
    assigned a long (+1) signal, those with ranks less than or equal to
    ``short_pct`` receive a short (‑1) signal, and all others get 0.  This
    mirrors the construction of classical cross‑sectional momentum factors
    where the strongest performers are bought and the weakest are sold【416002924589760†L24-L33】.

    Parameters
    ----------
    cs_rank : pandas.DataFrame
        DataFrame of cross‑sectional percentile ranks (values in (0, 1])
        indexed by date and with tickers as columns.  Typically the
        output of ``build_features(...)["cross_sectional_rank"]["cs_rank_252d"]``.
    long_pct : float, optional
        Fraction of assets to allocate to the long leg.  ``0.2`` means the
        top 20% by rank are long.
    short_pct : float, optional
        Fraction of assets to allocate to the short leg.  ``0.2`` means the
        bottom 20% by rank are short.

    Returns
    -------
    pandas.DataFrame
        DataFrame of signals with values in {‑1, 0, +1}.  Index and
        columns match ``cs_rank``.
    """
    signals = pd.DataFrame(index=cs_rank.index, columns=cs_rank.columns, dtype=float)
    long_threshold = 1.0 - long_pct
    short_threshold = short_pct
    signals[cs_rank >= long_threshold] = 1.0
    signals[cs_rank <= short_threshold] = -1.0
    signals[(cs_rank > short_threshold) & (cs_rank < long_threshold)] = 0.0
    return signals


def compute_vol_scaled_weights(
    signals: pd.DataFrame, vol: pd.DataFrame
) -> pd.DataFrame:
    """Apply volatility scaling to raw momentum signals.

    Each asset’s signal is divided by its recent volatility.  This gives
    larger weights to less volatile assets and smaller weights to more
    volatile ones.  The idea is supported by research showing that
    volatility scaling reduces crash risk and improves risk‑adjusted
    returns【511009017126348†L146-L152】.  After scaling, weights are
    normalised so that the sum of absolute weights equals 1 on each date.

    Parameters
    ----------
    signals : pandas.DataFrame
        DataFrame of raw signals (‑1, 0 or +1) indexed by date and
        columns being tickers.
    vol : pandas.DataFrame
        DataFrame of rolling volatility estimates indexed by date and
        columns being tickers.  Typically generated from
        ``build_features(...)["volatility"]["vol_63d"]``.

    Returns
    -------
    pandas.DataFrame
        DataFrame of scaled portfolio weights.  Weights sum to +1 for the
        long side and ‑1 for the short side, yielding 0 net exposure.
    """
    # Divide signals by volatility; avoid division by zero
    raw = signals / vol
    # Replace infinities and NaNs with zero
    raw = raw.replace([np.inf, -np.inf], 0.0).fillna(0.0)
    # Normalise so that sum of absolute weights equals 1 each day
    abs_sum = raw.abs().sum(axis=1)
    # Avoid division by zero when all signals are zero
    abs_sum = abs_sum.replace(0, np.nan)
    weights = raw.div(abs_sum, axis=0).fillna(0.0)
    return weights


def main() -> None:
    """Run the signal generation pipeline.

    This function locates the latest price panel, computes engineered
    features including cross‑sectional ranks and volatility, generates
    long‑short momentum signals, applies volatility scaling and writes
    the resulting signals and weights to disk with date stamps.
    """
    # Determine the base directory as the directory containing this script
    base_dir = Path(__file__).resolve().parent
    # Locate the prices directory.  In some project layouts the data directory
    # resides next to this module (base_dir/data), while in others it is one
    # level higher (base_dir.parent/data).  Try the local path first and
    # fall back to the parent if necessary.
    prices_dir = base_dir / "data" / "prices"
    if not prices_dir.exists():
        alt_dir = base_dir.parent / "data" / "prices"
        if alt_dir.exists():
            prices_dir = alt_dir
    # Load prices
    prices = load_latest_price_panel(prices_dir)
    # Compute engineered features; include cross‑sectional rank on 252‑day returns
    feats = build_features(
        prices,
        return_horizons=(1, 5, 21, 63, 252),
        vol_windows=(21, 63, 252),
        ma_window=200,
        drawdown_window=252,
        cs_rank_horizons=(252,),
    )
    # Extract the 252‑day cross‑sectional rank and 63‑day volatility
    cs_rank_252 = feats["cross_sectional_rank"]["cs_rank_252d"]
    vol_63 = feats["volatility"]["vol_63d"]
    # Generate raw signals (long/short/flat)
    signals = compute_cs_momentum_signals(cs_rank_252, long_pct=0.2, short_pct=0.2)
    # Apply volatility scaling to get weights
    weights = compute_vol_scaled_weights(signals, vol_63)
    # Construct output directory
    out_dir = base_dir / "data" / "signals"
    out_dir.mkdir(parents=True, exist_ok=True)
    # Save with date stamp
    stamp = date.today().isoformat()
    signals_file = out_dir / f"signals_cs_{stamp}.csv"
    weights_file = out_dir / f"weights_cs_{stamp}.csv"
    signals.to_csv(signals_file)
    weights.to_csv(weights_file)
    print(f"Saved signals to {signals_file}")
    print(f"Saved volatility-scaled weights to {weights_file}")


if __name__ == "__main__":
    main()